inferenceExtension:
  replicas: 1
  image:
    # Either image will work, you just need to bring the correct plugins per image. In this example we will bring the upstream default plugin
    ###################
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.2.1
    ###################
    # name: epp
    # hub: registry.k8s.io/gateway-api-inference-extension
    # tag: v0.5.1
    ###################
    pullPolicy: Always
  extProcPort: 9002
  
  # OPTION 1: Use default plugins-v2.yaml (current working setup)
  # pluginsConfigFile: "plugins-v2.yaml"
   
  # OPTION 2: Override with custom scorers - uncomment and modify as needed
  # pluginsConfigFile: "custom-scorers.yaml"
  # pluginsCustomConfig:
  #   custom-scorers.yaml: |
  #     apiVersion: inference.networking.x-k8s.io/v1alpha1
  #     kind: EndpointPickerConfig
  #     plugins:
  #       # Available scorer types:
  #       - type: single-profile-handler    # Basic request handler
  #       - type: round-robin-picker        # Simple round-robin load balancing
  #       - type: queue-scorer              # Queue depth-based scoring
  #       - type: kv-cache-scorer           # KV cache utilization scoring
  #       - type: prefix-cache-scorer       # Prefix cache awareness (approximate or precise)
  #         parameters:
  #           mode: approximate             # or "cache_tracking" for precise
  #       - type: random-picker             # Random endpoint selection
  #       - type: max-score-picker          # Select endpoint with highest score
  #     schedulingProfiles:
  #       - name: default
  #         plugins:
  #           - pluginRef: queue-scorer
  #             weight: 1.0                 # Queue depth weight
  #           - pluginRef: kv-cache-scorer  
  #             weight: 2.0                 # Cache utilization weight
  #           - pluginRef: max-score-picker # Final selection algorithm
  
  # OPTION 3: Simple round-robin (no intelligence) - uncomment to use
  # pluginsConfigFile: "round-robin.yaml"
  # pluginsCustomConfig:
  #   round-robin.yaml: |
  #     apiVersion: inference.networking.x-k8s.io/v1alpha1
  #     kind: EndpointPickerConfig
  #     plugins:
  #       - type: single-profile-handler
  #       - type: round-robin-picker
  #     schedulingProfiles:
  #       - name: default
  #         plugins:
  #           - pluginRef: round-robin-picker
  
  # OPTION 4: Queue-only scoring - ACTIVE EXAMPLE
  pluginsConfigFile: "queue-only.yaml"
  pluginsCustomConfig:
    queue-only.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
        - type: single-profile-handler
        - type: queue-scorer
        - type: max-score-picker
      schedulingProfiles:
        - name: default
          plugins:
            - pluginRef: queue-scorer
              weight: 1.0
            - pluginRef: max-score-picker

inferencePool:
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      # llm-d.ai/model: ms-simple-llm-d-modelservice
provider:
  name: none
