multinode: false

modelArtifacts:
  uri: "hf://meta-llama/Llama-3.1-8B-Instruct"
  name: "meta-llama/Llama-3.1-8B-Instruct"
  size: 50Gi
  authSecretName: "llm-d-hf-token"
  # Use PVC for persistent model storage
  volume:
    existingClaim: "model-storage"

routing:
  modelName: meta-llama/Llama-3.1-8B-Instruct
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      # name: infra-inference-scheduling-inference-gateway # set in helmfile

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    connector: nixlv2
    secure: false

  inferenceModel:
    create: false

  inferencePool:
    create: false
    # name: gaie-inference-scheduling # set in helmfile

  httpRoute:
    create: false

  epp:
    create: false

decode:
  create: true
  replicas: 4  # 4 replicas with TP=1 each (4 GPUs total: 1 per replica)
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enforce-eager"
      - "--host=0.0.0.0"               # Explicitly bind to all IPv4 addresses (fixes dual-stack issue)
      - "--max-model-len=4096"         # Higher context for 8B model (much smaller memory footprint)
      - "--tensor-parallel-size=1"     # Single GPU per pod (simpler, more reliable)
      - "--gpu-memory-utilization=0.80" # Higher utilization for smaller 8B model
      # --block-size removed (not needed for basic plugins-v2.yaml configuration)
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"  # Single GPU per pod
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 5557
        protocol: TCP
      - containerPort: 8200
        name: metrics
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"  # Single GPU per pod
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}

# PD disabled in this example
prefill:
  create: false
